### ISSUE TITLE
add login based on login API

### ISSUE THREAD

**Issue by Hameds** [Text-Mining/iOS-app#1]
[https://github.com/Text-Mining/Persian-NER/wiki/Panel-API#%D8%A7%D8%AD%D8%B1%D8%A7%D8%B2-%D9%87%D9%88%DB%8C%D8%AA](https://github.com/Text-Mining/Persian-NER/wiki/Panel-API#%D8%A7%D8%AD%D8%B1%D8%A7%D8%B2-%D9%87%D9%88%DB%8C%D8%AA)

**Comment by arashrasoulzadeh** [comment]
من چون با شبکه اجتماعی وارد شدم. رمزم رو نمیدونم 

چرا فراموشی کلمه عبور نداره؟

**Comment by arashrasoulzadeh** [comment]
جالب اینه با اونا هم لاگین نمیشه

**Comment by Hameds** [comment]
@arashrasoulzadeh با شبکه اجتماعی که وارد می‌شید می‌تونید پسورد هم در پروفایل انتخاب کنید. ورود رو چک می‌کنم. فراموشی کلمه عبور هم حق با شماست. اضافه می‌کنیم
